#!/bin/bash

. ./lib.sh

# node <CMD> <ID> [options]
cmd="$1"; shift
id="$(get_id redis $1)"
name="$(get_name redis $1)"; shift

case "$cmd" in
  "add")
    docker run --name $name -t -d -i planitar/redis
    log "Redis node created: $name ($(d_ip $name):6379)"
    if [ $# -gt 0 ]; then
      ./node slaveof $id $1
    fi
    ;;

  "rem")
    if [ "$id" == all ]; then
      d_rma redis
      log "Redis nodes removed: redis.*"
    else
      docker rm -f $name
      log "Redis node removed: $name"
    fi
    ;;

  "slaveof")
    mastername=$(get_name redis $1)
    masterip=$(d_ip $mastername)
    ./node cli $id slaveof $masterip 6379
    log "Redis node $name joined $mastername ($masterip:6379)"
    ;;

  "cli")
    redis-cli -h $(d_ip $name) -p 6379 "$@"
    ;;

  "name")
    echo $name
    ;;

  "ip")
    d_ip $name
    ;;

  "status")
    masterip="$1"
    if docker inspect $name >/dev/null 2>&1; then
      printf "%s (%s:%d)\n" $name $(d_ip $name) 6379
    else
      printf "%s (DOWN)\n" $name
    fi
    ;;

esac

# vim: ft=sh sw=2 et :
